# Site Configuration

# Basic Settings
lang: ko
timezone: Asia/Seoul

# Site Information
title: Hi,ijzereen
tagline: Neo-Brutalist Digital Chaos
description: PlayGround

# Author Information  
author: Ijzereen

email: ijzereen@gmail.com

social:
  name: Ijzereen
  email: ijzereen@gmail.com
  links:
    - https://github.com/ijzereen

# GitHub Settings
github:
  username: Ijzereen

# UI Labels and Text
ui:
  # Navigation and Buttons
  nav:
    search: "Search"
    randomize: "Randomize"
    restore: "Restore"
    chaos: "CHAOS"
    chaos_stop: "STOP"
    about: "Who is 철원"
    back: "← BACK"
    back_to_chaos: "← BACK TO CHAOS"
  
  # Categories and Tags
  categories:
    title: "CATEGORIES"
    all: "ALL"
  
  tags:
    title: "TAGS"
  
  # Windows and Popups
  windows:
    title: "window"
    greeting: ", how are you?"
    badge_id: "ID:"
    badge_issued: "/ ISSUED: TODAY"
    badge_title: "THE PRESIDENT"
    badge_portrait: "PORTRAIT"
  
  # Search
  search:
    title: "SEARCH"
    placeholder: "제목, 내용, 카테고리, 태그로 검색..."
    no_results: "검색 결과가 없습니다."

# Basic Jekyll Settings
baseurl: ""
paginate: 10

# Markdown Settings
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Default Settings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: false
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Build Settings
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Exclude from build
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"

# Plugin Settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives