# Site Configuration

# Basic Settings
lang: ko
timezone: Asia/Seoul

# Site Information
title: IJZEREEN
tagline: Resident of Room 0
description: 1인칭 책상 위의 포트폴리오 겸 기술 저널.

# Author Information
author: Ijzereen
email: ijzereen@gmail.com

social:
  name: Ijzereen
  email: ijzereen@gmail.com
  links:
    - https://github.com/ijzereen

github:
  username: Ijzereen

# Basic Jekyll Settings
baseurl: ""
paginate: 10

# Markdown Settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true

# Default Settings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: false
      permalink: /blog/:slug/

# Build Settings
sass:
  style: compressed

# Exclude from build
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "기획.md"
  - "*.config.js"
  - "package*.json"

# Plugin Settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Cache Control
future: false
safe: true
incremental: false
livereload: true
