/* AUTO-GENERATED by scripts/index-posts.py — do not edit by hand. */
window.POSTS_DATA = {
  "blog": [
    {
      "id": "2025-08-11-lexical-search",
      "title": "2025-08-11-Lexical-Search",
      "date": "2025-08-11",
      "file": "2025-08-11-Lexical-Search.md"
    }
  ],
  "book": [],
  "drawing": [
    {
      "id": "img-3508",
      "file": "IMG_3508.jpeg"
    },
    {
      "id": "img-3553",
      "file": "IMG_3553.jpeg"
    }
  ],
  "game": [],
  "movie": []
};
