#!/usr/bin/env python3
"""
index-profile.py — turn Profile/*.md into profile-data.js.

For each markdown file in Profile/, walks H2 sections and produces a
flat dict of i18n-shaped keys that gets merged into window.STRINGS by
i18n.jsx at load time. The output is written to profile-data.js at
repo root and loaded before i18n.jsx via index.html.

Heading conventions:
  ## <field> (EN)          → bilingual key, English half
  ## <field> (KO)          → bilingual key, Korean half
  ## <field> > <subfield>  → nested path, language-neutral
  Body that starts with `- ` → list (paired by index across EN/KO)

Run after editing any Profile/*.md:
  python3 scripts/index-profile.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROFILE_DIR = ROOT / 'Profile'
OUT = ROOT / 'profile-data.js'

H2_RE = re.compile(r'^##\s+(.+?)\s*$')
H1_RE = re.compile(r'^#\s')
LANG_SUFFIX_RE = re.compile(r'^(.+?)\s*\((EN|KO|en|ko)\)\s*$')
BULLET_RE = re.compile(r'^\s*[-*]\s+(.*)$')


def path_to_key(heading: str) -> str:
    """`exp > 1 > when` → `exp.1.when`."""
    parts = [p.strip().replace(' ', '_') for p in heading.split('>')]
    return '.'.join(p for p in parts if p)


def parse_md(text: str) -> dict:
    """Walk H2 sections, build a flat dict.

    Bilingual values become {en, ko} pairs. Bullet bodies become lists.
    Returns shape: { 'path.to.key': str | list | {en, ko} | {en: list, ko: list} }
    """
    sections: list[tuple[str, list[str]]] = []
    cur_heading = None
    cur_body: list[str] = []
    in_comment = False
    for line in text.splitlines():
        if '<!--' in line:
            in_comment = True
        if in_comment:
            if '-->' in line:
                in_comment = False
            continue
        m = H2_RE.match(line)
        if m:
            if cur_heading is not None:
                sections.append((cur_heading, cur_body))
            cur_heading = m.group(1)
            cur_body = []
        elif H1_RE.match(line):
            continue
        else:
            if cur_heading is not None:
                cur_body.append(line)
    if cur_heading is not None:
        sections.append((cur_heading, cur_body))

    out: dict = {}
    for heading, body_lines in sections:
        lang = None
        lm = LANG_SUFFIX_RE.match(heading)
        if lm:
            heading_clean = lm.group(1).strip()
            lang = lm.group(2).lower()
        else:
            heading_clean = heading.strip()
        key = path_to_key(heading_clean)

        bullets = [BULLET_RE.match(l).group(1).strip()
                   for l in body_lines if BULLET_RE.match(l)]
        body_text = '\n'.join(body_lines).strip()
        value: object = bullets if bullets else body_text

        if lang:
            entry = out.get(key)
            if not isinstance(entry, dict):
                entry = {}
            entry[lang] = value
            out[key] = entry
        else:
            out[key] = value
    return out


def expand_lists(prefix: str, data: dict) -> dict:
    """If a value is {en: list, ko: list}, expand to numbered subkeys.

    `values: {en: [a,b,c], ko: [가,나,다]}` becomes
    `values.1: {en: a, ko: 가}`, `values.2: ...`, `values.3: ...`.
    """
    out = {}
    for k, v in data.items():
        full = f'{prefix}.{k}' if prefix else k
        if isinstance(v, dict) and v and all(isinstance(x, list) for x in v.values()):
            n = max(len(x) for x in v.values())
            for i in range(n):
                pair = {lang: lst[i] for lang, lst in v.items() if i < len(lst)}
                out[f'{full}.{i + 1}'] = pair
        else:
            out[full] = v
    return out


def main() -> int:
    if not PROFILE_DIR.exists():
        print(f'Profile dir not found: {PROFILE_DIR}', file=sys.stderr)
        return 1
    combined: dict = {}
    for md_path in sorted(PROFILE_DIR.glob('*.md')):
        prefix = md_path.stem.lower()
        raw = parse_md(md_path.read_text(encoding='utf-8'))
        flat = expand_lists(prefix, raw)
        combined.update(flat)
    body = json.dumps(combined, ensure_ascii=False, indent=2)
    OUT.write_text(
        '/* AUTO-GENERATED by scripts/index-profile.py — do not edit by hand. */\n'
        f'window.PROFILE_STRINGS = {body};\n',
        encoding='utf-8',
    )
    print(f'wrote {OUT.relative_to(ROOT)} — {len(combined)} keys')
    return 0


if __name__ == '__main__':
    sys.exit(main())
