#!/usr/bin/env python3
"""
index-posts.py — scan Post/* for files and emit posts-data.js.

Why this script exists:
  The site has no build step (Babel-standalone in the browser), so it
  cannot list the filesystem at runtime. This script walks Post/<folder>/
  once, extracts metadata, and writes posts-data.js with a single
  window.POSTS_DATA global. index.html loads posts-data.js before
  config.jsx, and config.jsx merges those arrays into the category
  items[] — so dropping a new .md or image in a Post/* folder + running
  this script is enough to make it show up on the desktop.

Usage:
  python3 scripts/index-posts.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POST_DIR = ROOT / 'Post'
OUT = ROOT / 'posts-data.js'

IMAGE_EXTS = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.svg', '.avif'}
MD_EXTS = {'.md', '.markdown'}

FRONTMATTER_RE = re.compile(r'^---\r?\n(.*?)\r?\n---\r?\n', re.DOTALL)
KV_RE = re.compile(r'^([\w-]+):\s*(.+?)\s*$', re.MULTILINE)
DATE_PREFIX_RE = re.compile(r'^(\d{4}-\d{2}-\d{2})')


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding='utf-8', errors='replace')
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    out = {}
    for k, v in KV_RE.findall(m.group(1)):
        out[k.lower()] = v.strip().strip('"').strip("'")
    return out


def slugify(stem: str) -> str:
    s = stem.lower()
    s = re.sub(r'[^a-z0-9가-힣]+', '-', s)
    return s.strip('-') or 'item'


def item_for(file_path: Path) -> dict | None:
    name = file_path.name
    stem = file_path.stem
    ext = file_path.suffix.lower()
    if ext in IMAGE_EXTS:
        return {'id': slugify(stem), 'file': name}
    if ext in MD_EXTS:
        fm = parse_frontmatter(file_path)
        date = fm.get('date', '')
        if date:
            date = date.split(' ')[0]
        else:
            m = DATE_PREFIX_RE.match(stem)
            if m:
                date = m.group(1)
        return {
            'id': slugify(stem),
            'title': stem,
            'date': date,
            'file': name,
        }
    return None


def scan(folder: Path) -> list:
    if not folder.exists():
        return []
    items = []
    for entry in sorted(folder.iterdir()):
        if entry.is_file() and not entry.name.startswith('.'):
            it = item_for(entry)
            if it is not None:
                items.append(it)
    return items


def main() -> int:
    if not POST_DIR.exists():
        print(f'Post dir not found: {POST_DIR}', file=sys.stderr)
        return 1
    data: dict[str, list] = {}
    for sub in sorted(POST_DIR.iterdir()):
        if sub.is_dir() and not sub.name.startswith('.'):
            data[sub.name.lower()] = scan(sub)
    body = json.dumps(data, ensure_ascii=False, indent=2)
    OUT.write_text(
        '/* AUTO-GENERATED by scripts/index-posts.py — do not edit by hand. */\n'
        f'window.POSTS_DATA = {body};\n',
        encoding='utf-8',
    )
    counts = ', '.join(f'{k}: {len(v)}' for k, v in data.items())
    print(f'wrote {OUT.relative_to(ROOT)} — {counts}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
